package com.auramusic.app.ui.player

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.auramusic.app.subtitles.SubtitleInfo

@Composable
fun SubtitleSelectorDialog(
    availableSubtitles: List<SubtitleInfo>,
    selectedIndex: Int,
    onSubtitleSelected: (Int) -> Unit,
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier
) {
    var selected by remember(selectedIndex) { mutableStateOf(selectedIndex) }

    Column(
        modifier = modifier
            .fillMaxWidth()
            .padding(16.dp)
    ) {
        Text(
            text = "Select Subtitle",
            style = MaterialTheme.typography.titleLarge,
            modifier = Modifier.padding(bottom = 16.dp)
        )

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .clickable {
                    selected = -1
                    onSubtitleSelected(-1)
                    onDismiss()
                }
                .padding(vertical = 8.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            RadioButton(
                selected = selected == -1,
                onClick = {
                    selected = -1
                    onSubtitleSelected(-1)
                    onDismiss()
                }
            )
            Spacer(modifier = Modifier.width(8.dp))
            Text(
                text = "Off",
                style = MaterialTheme.typography.bodyLarge
            )
        }

        availableSubtitles.forEachIndexed { index, subtitle ->
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable {
                        selected = index
                        onSubtitleSelected(index)
                        onDismiss()
                    }
                    .padding(vertical = 8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                RadioButton(
                    selected = selected == index,
                    onClick = {
                        selected = index
                        onSubtitleSelected(index)
                        onDismiss()
                    }
                )
                Spacer(modifier = Modifier.width(8.dp))
                Column(modifier = Modifier.weight(1f)) {
                    Text(
                        text = subtitle.language,
                        style = MaterialTheme.typography.bodyLarge
                    )
                    if (subtitle.isAutoGenerated) {
                        Text(
                            text = "Auto-generated",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }
        }
    }
}

fun getLanguageDisplayName(code: String): String {
    return when (code) {
        "en" -> "English"
        "es" -> "Spanish"
        "fr" -> "French"
        "de" -> "German"
        "it" -> "Italian"
        "pt" -> "Portuguese"
        "ru" -> "Russian"
        "ja" -> "Japanese"
        "ko" -> "Korean"
        "zh" -> "Chinese"
        "sw" -> "Swahili"
        "la" -> "Latin"
        "ar" -> "Arabic"
        "hi" -> "Hindi"
        "nl" -> "Dutch"
        "pl" -> "Polish"
        "sv" -> "Swedish"
        "tr" -> "Turkish"
        "vi" -> "Vietnamese"
        "th" -> "Thai"
        "id" -> "Indonesian"
        "ms" -> "Malay"
        "el" -> "Greek"
        "he" -> "Hebrew"
        "cs" -> "Czech"
        "hu" -> "Hungarian"
        "ro" -> "Romanian"
        "uk" -> "Ukrainian"
        else -> code.uppercase()
    }
}