package com.auramusic.app.subtitles

data class SubtitleInfo(
    val url: String,
    val format: String,
    val language: String,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val cachedContent: String? = null,
    val cachedFilePath: String? = null
)
